version: '3.7'

services:
  django:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - redis
      - postgres
  postgres:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - ./.env.prod
  celeryworker:
    build: ./app
    command: celery -A daytrader worker --loglevel=DEBUG
    volumes:
      - ./app:/usr/src/app
    env_file:
      - ./.env.dev
    depends_on:
      - django
      - redis
      - postgres
  celerybeat:
    build: ./app
    command: celery -A daytrader beat
    volumes:
      - ./app:/usr/src/app
    env_file:
      - ./.env.dev
    depends_on:
      - django
      - redis
      - postgres
  nextjs:
    build: ./frontend 
    depends_on:
      - django
    ports:
      - 3000:3000
    stdin_open: true
    volumes:
        - ./frontend:/usr/src/app/my-app
        - /usr/src/app/my-app/node_modules
  redis:
    image: redis:6-alpine

volumes:
  postgres_data: