version: '3.7'

services:
  django:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn daytrader.asgi:application -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  celeryworker:
    build: ./app
    command: celery -A daytrader worker --loglevel=DEBUG
    volumes:
      - ./app:/usr/src/app
    env_file:
      - ./.env.prod
    depends_on:
      - django
      - redis
      - postgres
  celerybeat:
    build: ./app
    command: celery -A daytrader beat --loglevel=DEBUG
    volumes:
      - ./app:/usr/src/app
    env_file:
      - ./.env.prod
    depends_on:
      - django
      - redis
      - postgres
  nextjs:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    depends_on:
      - django
  redis:
    image: redis:6-alpine
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 80:80
    depends_on:
      - django

volumes:
  postgres_data:
  static_volume: