version: '3.7'

services:
  django:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    expose:
      - 8000
    env_file:
      - ./.env.dev
    depends_on:
      - redis
      - postgres
      - selenium
  postgres:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - ./.env.prod
  celeryworker:
    build: ./app
    command: celery -A daytrader worker --loglevel=DEBUG
    volumes:
      - ./app:/usr/src/app
    env_file:
      - ./.env.dev
    depends_on:
      - django
      - redis
      - postgres
  celerybeat:
    build: ./app
    command: celery -A daytrader beat --loglevel=DEBUG
    volumes:
      - ./app:/usr/src/app
    env_file:
      - ./.env.dev
    depends_on:
      - django
      - redis
      - postgres
  nextjs:
    build: ./frontend 
    depends_on:
      - django
    stdin_open: true
    volumes:
        - ./frontend:/usr/src/app/my-app
        - /usr/src/app/my-app/node_modules
  redis:
    image: redis:6-alpine
  selenium:
    image: selenium/standalone-chrome
    ports:
      - "5900:5900"
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 1337:80
    depends_on:
      - django

volumes:
  postgres_data:
  static_volume: