# Generated by Django 3.2.4 on 2021-06-13 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0004_auto_20210613_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decisionhistory',
            name='confidence',
            field=models.FloatField(),
        ),
    ]
