# Generated by Django 3.2.4 on 2021-06-19 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0005_alter_decisionhistory_confidence'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DecisionHistory',
            new_name='Decision',
        ),
    ]
