# Generated by Django 3.2.4 on 2021-06-25 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0006_rename_decisionhistory_decision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decision',
            name='tradeDate',
            field=models.DateField(),
        ),
    ]
