# Generated by Django 3.2.5 on 2021-07-03 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0008_auto_20210629_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decision',
            name='confidence',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
