# Generated by Django 3.2.5 on 2021-07-04 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0009_alter_decision_confidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
