# Generated by Django 3.2.5 on 2021-07-05 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0013_stock_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='exchange',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
