# Generated by Django 3.2.5 on 2021-07-08 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0015_stock_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='decision',
            name='long',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='listed',
            field=models.BooleanField(default=False),
        ),
    ]
