# Generated by Django 3.2.5 on 2021-07-08 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0016_auto_20210708_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='listed',
            field=models.BooleanField(null=True),
        ),
    ]
