# Generated by Django 3.2.5 on 2021-07-08 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0017_alter_stock_listed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='listed',
            field=models.NullBooleanField(default=None),
        ),
    ]
