# Generated by Django 3.2.5 on 2021-07-13 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0020_auto_20210710_1518'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='decision',
            options={'ordering': ['-created_at']},
        ),
    ]
