# Generated by Django 3.2.5 on 2021-07-13 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0021_alter_decision_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='decision',
            options={'ordering': ['created_at']},
        ),
    ]
