# Generated by Django 3.2.5 on 2021-07-16 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0022_alter_decision_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='decision',
            old_name='closingPrice',
            new_name='closing_price',
        ),
        migrations.RenameField(
            model_name='decision',
            old_name='openPrice',
            new_name='open_price',
        ),
        migrations.RenameField(
            model_name='decision',
            old_name='tradeDate',
            new_name='trade_date',
        ),
    ]
