# Generated by Django 3.2.4 on 2021-06-13 21:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0002_auto_20210613_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='decisionhistory',
            name='closingPrice',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='decisionhistory',
            name='confidence',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='decisionhistory',
            name='openPrice',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='decisionhistory',
            name='tradeDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 13, 21, 37, 50, 107139, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
