# Generated by Django 3.2.4 on 2021-06-13 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0003_auto_20210613_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decisionhistory',
            name='closingPrice',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='decisionhistory',
            name='openPrice',
            field=models.FloatField(),
        ),
    ]
