# Generated by Django 3.2.4 on 2021-07-01 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210701_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='daily_emails',
            field=models.BooleanField(default=False),
        ),
    ]
